name: book_my_movie_app_frontend
description: A movie booking app inspired by BookMyShow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.1.0   # for env
  # UI
  # cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  barcode_widget: ^2.0.4

  # State & navigation
  # provider: ^6.1.1
  go_router: ^13.2.4

  # Networking
  dio: ^5.4.1
  # shared_preferences: ^2.2.2
  # flutter_dotenv: ^5.1.0

  # Utilities
  # intl: ^0.19.0
  # flutter_secure_storage: ^9.0.0   # optional, for tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/   # images here
    - images/